name: "V_Track"
language: python
read_only: true

# STRICT ANALYSIS-ONLY MODE - KHÔNG ĐƯỢC SỬA FILE
excluded_tools:
  # File operations - KHÔNG được tạo/sửa/xóa file
  - create_text_file
  - delete_lines
  - insert_at_line
  - insert_after_symbol
  - insert_before_symbol
  - replace_lines
  - replace_symbol_body
  
  # Shell operations - KHÔNG được chạy lệnh
  - execute_shell_command
  
  # Memory operations - Chỉ được đọc, không được ghi
  - write_memory
  - delete_memory
  
  # Project operations - Không được thay đổi project
  - switch_modes

ignored_paths:
  - "serena"
  - "__pycache__"
  - ".venv"
  - "*.pyc"
  - "node_modules"
  - ".git"

# Initial prompt nhắc nhở luôn
initial_prompt: |
  ⚠️ ANALYSIS-ONLY MODE ⚠️
  - CHỈ được đọc và phân tích code
  - TUYỆT ĐỐI KHÔNG được tạo, sửa, xóa file
  - TUYỆT ĐỐI KHÔNG được chạy lệnh shell
  - Chỉ đưa ra gợi ý và phân tích